### ISSUE TITLE
Plastic panel thickness

### ISSUE THREAD

**Issue by 2lostkiwis** [TheBeachLab/BeachLab_flip_flap#1]
Not sure if this is the right place, but I am trying to figure out how thick the plastic should be for the panels for the enclosure. My current guess is 5mm but it would be great if you could confirm this for me. Many thanks.

**Comment by TheBeachLab** [comment]
Sorry about the delay, the thickness is 3 mm if you are using the V1 design files. But we are currently working in a second iteration of foldable cardboard.
