### ISSUE TITLE
CAD Files are incompatible with new Kokopelli

### ISSUE THREAD

**Issue by hlieberman** [TheBeachLab/BeachLab_flip_flap#2]
The CAD files for the circuit boards no longer work with newer versions of kokopelli.  There are several errors, some which are easy to resolve, and some which are harder.

**Comment by TheBeachLab** [comment]
I know. I am pushing the former kokopelli in a new repository and I get back to you

**Comment by hlieberman** [comment]
Hello!

I just wanted to check in to see if you were able to upload a copy of
kokopelli 0.05 anywhere.

Sincerely,

-- Harlan Lieberman-Berg

**Comment by TheBeachLab** [comment]
I uploaded it to electronics folder. I wrote the instructions. Let me know how it goes
